import JsonLdInjector from "@/lib/jsonld-injector";
import PortfolioThemeProvider from "@/lib/theme";
import Header from "@/ui/header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <JsonLdInjector />
                <AppRouterCacheProvider>
                    <PortfolioThemeProvider>
                        <Header />
                        {children}
                    </PortfolioThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
