import classNames from "classnames";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Montserrat } from "next/font/google";
import { Metadata } from "next";
import Link from "next/link";

config.autoAddCss = false;
const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Rio&apos;s Portfolio</title>
      </head>
      <body
        className={classNames(
          "bg-slate-50 text-slate-950 dark:bg-slate-800 dark:text-slate-50",
          mont.className
        )}
      >
        <nav>
          <div className="container h-16 px-8 mx-auto max-w-full flex justify-between items-center">
            <Link href="/" className="font-bold">Eshwin Rio</Link>
            <ul>
              <li>
                <Link href="/" className="font-medium hover:underline">Home</Link>
              </li>
            </ul>
          </div>
        </nav>
        
        {children}

        <footer className="bg-slate-200 text-slate-950 dark:bg-slate-700 dark:text-slate-50">
          <div className="container py-8 mx-auto max-w-4xl">
            <p className="text-sm text-slate-300">© 2023 Eshwin Rio</p>
          </div>
        </footer>

      </body>
    </html>
  );
}
